
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  CPM_USE_NAMED_CACHE_DIRECTORIES: TRUE

jobs:
  windows:
    name: Windows (${{ matrix.arch.name }}, ${{ matrix.config.name }})
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
        - { name: x86, flags: -A Win32 }
        - { name: x64, flags: -A x64 }
        config:
        - { name: static, flags: -D BUILD_SHARED_LIBS=0 }
        - { name: shared, flags: -D BUILD_SHARED_LIBS=1 }
        build_type: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      id: cache-cpm
      with:
        path: '**/cpm_modules'
        key: windows-cpm-modules-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Configure
      run: cmake -B build ${{ matrix.arch.flags }} ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Install
      run: cmake --install build --config ${{ matrix.build_type }} --prefix install/libquack-${{ github.sha }}

    - uses: actions/upload-artifact@v3
      with:
        name: libquack-windows-${{ matrix.arch.name }}-${{ matrix.config.name }}-${{ matrix.build_type }}-${{ github.sha }}
        path: install/*

# mingw:
#   name: MinGW (${{ matrix.arch.name }}, ${{ matrix.config.name }})
#   runs-on: windows-latest
#
#   strategy:
#     fail-fast: false
#
#     matrix:
#       arch:
#       - { name: x86, flags: -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++ }
#       - { name: x64, flags: -D CMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ }
#       config:
#       - { name: static, flags: -D BUILD_SHARED_LIBS=0 }
#       - { name: shared, flags: -D BUILD_SHARED_LIBS=1 }
#
#   steps:
#   - uses: actions/checkout@v3
#
#   - uses: actions/cache@v3
#     id: cache-cpm
#     with:
#       path: '**/cpm_modules'
#       key: mingw-cpm-modules-${{ hashFiles('**/CMakeLists.txt') }}
#
#   - name: Configure
#     run: cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug ${{ matrix.arch.flags }} ${{ matrix.config.flags }}
#
#   - name: Build
#     run: cmake --build build
#
#   - name: Install
#     run: cmake --install build --prefix install/libquack-dbg
#
#   - uses: actions/upload-artifact@v3
#     with:
#       name: libquack-mingw-${{ matrix.arch.name }}-${{ matrix.config.name }}-${{ github.sha }}
#       path: install/*

  linux:
    name: Linux (${{ matrix.compiler.name }}, ${{ matrix.build_type }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
        - { name: GNU, c: gcc, cxx: g++ }
        - { name: Clang, c: clang, cxx: clang++ }
        build_type: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      id: cache-cpm
      with:
        path: '**/cpm_modules'
        key: linux-cpm-modules-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build libgl1-mesa-dev libgles2-mesa-dev xorg-dev libopenal-dev

    - name: Configure
      run: >
        cmake -B build -G "Ninja"
        -D BUILD_SHARED_LIBS=0
        -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -D CMAKE_C_COMPILER=${{ matrix.compiler.c }}
        -D CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}

    - name: Build
      run: cmake --build build

